package com.pp.workflow.dao;

import com.pp.workflow.domain.TbEvection;
import com.pp.workflow.domain.TbEvectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbEvectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int countByExample(TbEvectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int deleteByExample(TbEvectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int insert(TbEvection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int insertSelective(TbEvection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    List<TbEvection> selectByExample(TbEvectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    TbEvection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbEvection record, @Param("example") TbEvectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbEvection record, @Param("example") TbEvectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbEvection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_evection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbEvection record);
}