package com.pp.workflow.dao;

import com.pp.workflow.domain.TbFlow;
import com.pp.workflow.domain.TbFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int countByExample(TbFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int deleteByExample(TbFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int insert(TbFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int insertSelective(TbFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    List<TbFlow> selectByExample(TbFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    TbFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbFlow record, @Param("example") TbFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbFlow record, @Param("example") TbFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbFlow record);
}