package com.pp.workflow.domain;

import java.io.Serializable;

public class TbFlow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.flowname
     *
     * @mbggenerated
     */
    private String flowname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.flowkey
     *
     * @mbggenerated
     */
    private String flowkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.filepath
     *
     * @mbggenerated
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_flow.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.id
     *
     * @return the value of tb_flow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.id
     *
     * @param id the value for tb_flow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.flowname
     *
     * @return the value of tb_flow.flowname
     *
     * @mbggenerated
     */
    public String getFlowname() {
        return flowname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.flowname
     *
     * @param flowname the value for tb_flow.flowname
     *
     * @mbggenerated
     */
    public void setFlowname(String flowname) {
        this.flowname = flowname == null ? null : flowname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.flowkey
     *
     * @return the value of tb_flow.flowkey
     *
     * @mbggenerated
     */
    public String getFlowkey() {
        return flowkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.flowkey
     *
     * @param flowkey the value for tb_flow.flowkey
     *
     * @mbggenerated
     */
    public void setFlowkey(String flowkey) {
        this.flowkey = flowkey == null ? null : flowkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.filepath
     *
     * @return the value of tb_flow.filepath
     *
     * @mbggenerated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.filepath
     *
     * @param filepath the value for tb_flow.filepath
     *
     * @mbggenerated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.state
     *
     * @return the value of tb_flow.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.state
     *
     * @param state the value for tb_flow.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flow.createtime
     *
     * @return the value of tb_flow.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flow.createtime
     *
     * @param createtime the value for tb_flow.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_flow
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flowname=").append(flowname);
        sb.append(", flowkey=").append(flowkey);
        sb.append(", filepath=").append(filepath);
        sb.append(", state=").append(state);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}